#pragma once

#define THREAD_CANCEL_STATE_ENABLED 1
#define THREAD_CANCEL_STATE_DISABLED 0

#define THREAD_CANCEL_TYPE_ASYNC 0
#define THREAD_CANCEL_TYPE_DEFERRED 1

#define THREAD_CANCEL_CANCELATION_ISCANCELED 1
#define THREAD_CANCEL_CANCELATION_NOTCANCELED 0
//enum THREAD_CANCEL_STATE {
//    ENABLED = 1, DISABLED = 0
//};
//enum THREAD_CANCEL_TYPE {
//    ASYNCHRONOUS = 0, DEFERRED = 1
//};
//enum THREAD_CANCELATION {
//    ISCANCELED = 1, NOTCANCELED = 0
//};